### ISSUE TITLE
undefined method エラーが出る

### ISSUE THREAD

**Issue by hakuoku** [aozorahack/aozora2html#106]
PowerShell 7.2.2、ruby 3.1.3p185、aozora2html 3.0.0、rubyzip 2.3.2（双方最新版です）にて、Web上のzipフォルダを変換しようとすると以下のエラーが出ます。

```
> aozora2html https://www.aozora.gr.jp/cards/000051/files/1441_ruby.zip web_1441.html

C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/aozora2html-3.0.0/lib/aozora2html/zip.rb:11:in `block in unzip': undefined method `extract' for nil:NilClass (NoMethodError)

        entry.extract(textfilename)
             ^^^^^^^^
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rubyzip-2.3.2/lib/zip/file.rb:125:in `open'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/aozora2html-3.0.0/lib/aozora2html/zip.rb:9:in `unzip'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/aozora2html-3.0.0/bin/aozora2html:66:in `block in <top (required)>'
        from C:/Ruby31-x64/lib/ruby/3.1.0/tmpdir.rb:96:in `mktmpdir'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/aozora2html-3.0.0/bin/aozora2html:42:in `<top (required)>'
        from C:/Ruby31-x64/bin/aozora2html:32:in `load'
        from C:/Ruby31-x64/bin/aozora2html:32:in `<main>'
```

**Comment by gemmaro** [comment]
Dockerの`ruby:3.1.3`でaozora2html (272f46dc3a7b9b48e41696575974c2a500efdbb1), rubyzipのバージョンを揃えて試しましたが再現しませんでした。
WSLではどうなりますか。

**Comment by hakuoku** [comment]
WSLのUbuntu 22.04.2、rbenvによる環境構築で各バージョンを揃えて試したところ成功しました。
ちなみに私の環境では最初にWSLにLinuxディストリビューションが一切入っていなかったのでそれが原因かと思い、wslを抜けてからPowerShellで再度試しましたがやはり同じエラーが出ました。

**Comment by takahashim** [comment]
反応遅くなりました。
Macで確認したところでは、Ruby 3.1.3でも3.2.2でも特に問題なく動作しますね…。

エラーメッセージから判断する限りでは、`entry = zip_file.glob('*.txt').first`のところで`entry`がnilになっているようですが、そうなる要因が思いつきませんでした。

Windowsでの確認はすぐにはできなさそうなので、もう少々お待ちいただけるとありがたいです。
